[package]
name = "xz-sys"
version = "5.2.5"
authors = ["Sergey Solodovnikov"]
edition = "2018"
links = "lzma"
build = "build.rs"

[lib]
crate-type = ["lib"]

[build-dependencies]
autotools = "0.2.1"
pkg-config = "0.3"
build-deps = "0.1"