//bindgen wraper

#include <archive.h>
#include <archive_entry.h>

enum
{
    ARCHIVE_STATUS_EOF = ARCHIVE_EOF,
    ARCHIVE_STATUS_OK = ARCHIVE_OK,
    ARCHIVE_STATUS_RETRY = ARCHIVE_RETRY,
    ARCHIVE_STATUS_WARN = ARCHIVE_WARN,
    ARCHIVE_STATUS_FAILED = ARCHIVE_FAILED,
    ARCHIVE_STATUS_FATAL = ARCHIVE_FATAL
};