[package]
name = "unrar-sdk-sys"
version = "0.1.0"
authors = ["Sergey Solodovnikov <elementa.ru@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
libc = "0.2"
num-traits = "0.2"
num-derive = "0.2"

[build-dependencies]
cc = "1.0"
