[package]
name = "leptonica-rs"
version = "0.1.0"
authors = ["Sergey Solodovnikov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
thiserror = "1.0"
leptonica-sys = { path = "../leptonica-sys" }
